package com.gestionplanning.ecr;

import com.fasterxml.jackson.annotation.JsonAutoDetect;

import com.gestionplanning.action.EcrActionDto;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@JsonAutoDetect(fieldVisibility = JsonAutoDetect.Visibility.ANY)
public class EcrRequestDto {
    private Long id;
    private Integer accessInternalNumber;
    private String modificationNumber;
    private String client;
    private String product;
    private String finishedProducts;
    private String modificationProject;
    private LocalDate receptionDate;
    private LocalDate sopDate;
    private String pilot;
    private String previousPilot;
    private String modificationReason;
    private String modificationDetail;
    private String beforePhoto;
    private String beforePhotoContentType;
    private Long beforePhotoFileSize;
    private String beforePhotoUrl;
    private String beforePhotoPublicId;
    private String beforePhotoResourceType;
    private String afterPhoto;
    private String afterPhotoContentType;
    private Long afterPhotoFileSize;
    private String afterPhotoUrl;
    private String afterPhotoPublicId;
    private String afterPhotoResourceType;
    private String mixability;
    private String dossierReview;
    private String technicalFile;
    private String clientPlanning;
    private String internalPlanning;
    private String oilList;
    private String report;
    private boolean digitChange;
    private boolean componentChange;
    private boolean processChange;
    private boolean supplierChange;
    private boolean newVersion;
    private boolean feasibilityValidation;
    private LocalDate feasibilityValidationDate;
    private boolean internalCostingStatus;
    private LocalDate internalCostingDate;
    private boolean internalVpValidation;
    private LocalDate internalVpValidationDate;
    private boolean customerValidation;
    private LocalDate customerValidationDate;
    private boolean ppapValidation;
    private LocalDate ppapValidationDate;
    private boolean closureStatus;
    private LocalDate closureDate;
    private boolean closureRequested;
    private LocalDate closureRequestedDate;
    private String closureRequestedBy;
    private boolean cancelledStatus;
    private LocalDate cancelledDate;
    private EcrStage cancelledFromStage;
    private boolean archived;
    private String accessProjectTimeline;
    private String accessProjectManagement;
    private String accessProductDevelopment;
    private String accessProcessDevelopment;
    private String accessProductionSetup;
    private String accessLaunch;
    private String accessProjectCancelled;
    private EcrStage currentStage;
    private List<ChecklistItemDto> checklistItems = new ArrayList<>();
    private List<EcrActionDto> initialActions = new ArrayList<>();

    public static EcrRequestDto from(EcrRequest request) {
        if (request == null) {
            return null;
        }
        EcrRequestDto dto = new EcrRequestDto();
        dto.id = request.getId();
        dto.accessInternalNumber = request.getAccessInternalNumber();
        dto.modificationNumber = request.getModificationNumber();
        dto.client = request.getClient();
        dto.product = request.getProduct();
        dto.finishedProducts = request.getFinishedProducts();
        dto.modificationProject = request.getModificationProject();
        dto.receptionDate = request.getReceptionDate();
        dto.sopDate = request.getSopDate();
        dto.pilot = request.getPilot();
        dto.previousPilot = request.getPreviousPilot();
        dto.modificationReason = request.getModificationReason();
        dto.modificationDetail = request.getModificationDetail();
        dto.beforePhoto = request.getBeforePhoto();
        dto.beforePhotoContentType = request.getBeforePhotoContentType();
        dto.beforePhotoFileSize = request.getBeforePhotoFileSize();
        dto.beforePhotoUrl = request.getBeforePhotoUrl();
        dto.beforePhotoPublicId = request.getBeforePhotoPublicId();
        dto.beforePhotoResourceType = request.getBeforePhotoResourceType();
        dto.afterPhoto = request.getAfterPhoto();
        dto.afterPhotoContentType = request.getAfterPhotoContentType();
        dto.afterPhotoFileSize = request.getAfterPhotoFileSize();
        dto.afterPhotoUrl = request.getAfterPhotoUrl();
        dto.afterPhotoPublicId = request.getAfterPhotoPublicId();
        dto.afterPhotoResourceType = request.getAfterPhotoResourceType();
        dto.mixability = request.getMixability();
        dto.dossierReview = request.getDossierReview();
        dto.technicalFile = request.getTechnicalFile();
        dto.clientPlanning = request.getClientPlanning();
        dto.internalPlanning = request.getInternalPlanning();
        dto.oilList = request.getOilList();
        dto.report = request.getReport();
        dto.digitChange = request.isDigitChange();
        dto.componentChange = request.isComponentChange();
        dto.processChange = request.isProcessChange();
        dto.supplierChange = request.isSupplierChange();
        dto.newVersion = request.isNewVersion();
        dto.feasibilityValidation = request.isFeasibilityValidation();
        dto.feasibilityValidationDate = request.getFeasibilityValidationDate();
        dto.internalCostingStatus = request.isInternalCostingStatus();
        dto.internalCostingDate = request.getInternalCostingDate();
        dto.internalVpValidation = request.isInternalVpValidation();
        dto.internalVpValidationDate = request.getInternalVpValidationDate();
        dto.customerValidation = request.isCustomerValidation();
        dto.customerValidationDate = request.getCustomerValidationDate();
        dto.ppapValidation = request.isPpapValidation();
        dto.ppapValidationDate = request.getPpapValidationDate();
        dto.closureStatus = request.isClosureStatus();
        dto.closureDate = request.getClosureDate();
        dto.closureRequested = request.isClosureRequested();
        dto.closureRequestedDate = request.getClosureRequestedDate();
        dto.closureRequestedBy = request.getClosureRequestedBy();
        dto.cancelledStatus = request.isCancelledStatus();
        dto.cancelledDate = request.getCancelledDate();
        dto.cancelledFromStage = request.getCancelledFromStage();
        dto.archived = request.isArchived();
        dto.accessProjectTimeline = request.getAccessProjectTimeline();
        dto.accessProjectManagement = request.getAccessProjectManagement();
        dto.accessProductDevelopment = request.getAccessProductDevelopment();
        dto.accessProcessDevelopment = request.getAccessProcessDevelopment();
        dto.accessProductionSetup = request.getAccessProductionSetup();
        dto.accessLaunch = request.getAccessLaunch();
        dto.accessProjectCancelled = request.getAccessProjectCancelled();
        dto.currentStage = request.getCurrentStage();
        dto.checklistItems = request.getChecklistItems() == null ? new ArrayList<>() : request.getChecklistItems().stream().map(ChecklistItemDto::from).collect(Collectors.toList());
        dto.initialActions = request.getInitialActions() == null ? new ArrayList<>() : request.getInitialActions().stream().map(EcrActionDto::from).collect(Collectors.toList());
        return dto;
    }

    public EcrRequest toEntity() {
        EcrRequest request = new EcrRequest();
        request.setAccessInternalNumber(accessInternalNumber);
        request.setModificationNumber(modificationNumber);
        request.setClient(client);
        request.setProduct(product);
        request.setFinishedProducts(finishedProducts);
        request.setModificationProject(modificationProject);
        request.setReceptionDate(receptionDate);
        request.setSopDate(sopDate);
        request.setPilot(pilot);
        request.setPreviousPilot(previousPilot);
        request.setModificationReason(modificationReason);
        request.setModificationDetail(modificationDetail);
        request.setBeforePhoto(beforePhoto);
        request.setBeforePhotoContentType(beforePhotoContentType);
        request.setBeforePhotoFileSize(beforePhotoFileSize);
        request.setBeforePhotoUrl(beforePhotoUrl);
        request.setBeforePhotoPublicId(beforePhotoPublicId);
        request.setBeforePhotoResourceType(beforePhotoResourceType);
        request.setAfterPhoto(afterPhoto);
        request.setAfterPhotoContentType(afterPhotoContentType);
        request.setAfterPhotoFileSize(afterPhotoFileSize);
        request.setAfterPhotoUrl(afterPhotoUrl);
        request.setAfterPhotoPublicId(afterPhotoPublicId);
        request.setAfterPhotoResourceType(afterPhotoResourceType);
        request.setMixability(mixability);
        request.setDossierReview(dossierReview);
        request.setTechnicalFile(technicalFile);
        request.setClientPlanning(clientPlanning);
        request.setInternalPlanning(internalPlanning);
        request.setOilList(oilList);
        request.setReport(report);
        request.setDigitChange(digitChange);
        request.setComponentChange(componentChange);
        request.setProcessChange(processChange);
        request.setSupplierChange(supplierChange);
        request.setNewVersion(newVersion);
        request.setFeasibilityValidation(feasibilityValidation);
        request.setFeasibilityValidationDate(feasibilityValidationDate);
        request.setInternalCostingStatus(internalCostingStatus);
        request.setInternalCostingDate(internalCostingDate);
        request.setInternalVpValidation(internalVpValidation);
        request.setInternalVpValidationDate(internalVpValidationDate);
        request.setCustomerValidation(customerValidation);
        request.setCustomerValidationDate(customerValidationDate);
        request.setPpapValidation(ppapValidation);
        request.setPpapValidationDate(ppapValidationDate);
        request.setClosureStatus(closureStatus);
        request.setClosureDate(closureDate);
        request.setClosureRequested(closureRequested);
        request.setClosureRequestedDate(closureRequestedDate);
        request.setClosureRequestedBy(closureRequestedBy);
        request.setCancelledStatus(cancelledStatus);
        request.setCancelledDate(cancelledDate);
        request.setCancelledFromStage(cancelledFromStage);
        request.setArchived(archived);
        request.setAccessProjectTimeline(accessProjectTimeline);
        request.setAccessProjectManagement(accessProjectManagement);
        request.setAccessProductDevelopment(accessProductDevelopment);
        request.setAccessProcessDevelopment(accessProcessDevelopment);
        request.setAccessProductionSetup(accessProductionSetup);
        request.setAccessLaunch(accessLaunch);
        request.setAccessProjectCancelled(accessProjectCancelled);
        request.setCurrentStage(currentStage);
        request.setInitialActions(initialActions == null ? new ArrayList<>() : initialActions.stream().map(EcrActionDto::toEntity).collect(Collectors.toList()));
        return request;
    }

    public Long getId() { return id; }
    public List<ChecklistItemDto> getChecklistItems() { return checklistItems; }
}
