export const emptyEcrForm = {
  accessInternalNumber: "",
  modificationNumber: "",
  client: "",
  product: "",
  finishedProducts: "",
  modificationProject: "",
  modificationReason: "",
  modificationDetail: "",
  beforePhotoFile: null,
  afterPhotoFile: null,
  mixability: "",
  dossierReview: "",
  receptionDate: "",
  progressMailIntervalDays: "",
  sopDate: "",
  pilot: "",
  digitChange: false,
  componentChange: false,
  processChange: false,
  supplierChange: false,
  newVersion: false,
  currentStage: "FEASIBILITY_VALIDATION",
  initialActions: []
};

export const emptyActionForm = {
  topicRisk: "",
  title: "",
  stage: "",
  responsible: "",
  validator: "",
  criticality: "3-faible",
  expectedEvidence: "",
  proofDocumentFile: null,
  proofDocumentLinkName: "",
  proofDocumentLinkUrl: "",
  evidence: "",
  evidenceFile: null,
  evidenceLinkName: "",
  evidenceLinkUrl: "",
  deadline: "",
  date1: "",
  date2: "",
  date3: "",
  startDate: "",
  endDate: "",
  workDurationDays: 1,
  dependsOnActionId: "",
  dependencyAnchor: "OUTPUT",
  status: "TODO",
  evidenceRequired: false,
  comment: "",
  dossierReview: ""
};

export const emptyPlanningRuleForm = {
  stage: "FEASIBILITY_VALIDATION",
  appliesToModification: true,
  appliesToNewProject: true,
  actionTitle: "",
  topicRisk: "",
  responsible: "",
  validator: "",
  criticality: "3-faible",
  expectedEvidence: "",
  proofDocumentFile: null,
  proofDocumentLinkName: "",
  proofDocumentLinkUrl: "",
  evidenceRequired: false,
  dependencyActionTitle: "",
  dependencyAnchor: "OUTPUT",
  routineAction: false,
  recurrenceIntervalDays: 7,
  durationDays: 1
};

export const emptyFinishedProductForm = {
  client: "",
  project: "",
  partNumber: "",
  designation: "",
  customerPn: "",
  product: "",
  coiffeIndex: "",
  drawingIndex: "",
  reducedCode: "",
  salePrice: "",
  productionIntegrationDate: "",
  comments: ""
};

export const emptyUserForm = {
  fullName: "",
  username: "",
  jobTitle: "",
  matricule: "",
  email: "",
  password: "",
  phone: "",
  chef1: "",
  chef2: "",
  role: "CHEF_DE_PROJET",
  profilePhotoUrl: "",
  profilePhotoFile: null,
  enabled: true
};
