spring.application.name=backend
server.address=0.0.0.0
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/plannings
#spring.datasource.url=jdbc:postgresql://postgres:5432/store

spring.datasource.username=postgres
spring.datasource.password=supersecret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false

spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.sql.init.mode=always
spring.sql.init.mode=never

spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.jdbc.batch_versioned_data=true
application.security.jwt.secret-key=2b36a335c2c192370d18247f821b843bd18bcf06da565dd4ddc94860bbd84ecc
# a day
application.security.jwt.expiration=86400000
# 7 days
application.security.jwt.refresh-token.expiration=604800000
store.batchsage.prefix=REC
store.batchsage.digits=6
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dlsnmkiub}
cloudinary.api-key=${CLOUDINARY_API_KEY:966399145369398}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:Xfs1aysqZpjychABbsWPJ7_E3Mc}
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kameltounsi220@gmail.com
spring.mail.password=fpbtrojykwjpylqv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8

spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
app.alert.admin.email=f.chalbi@sagetunisia.com
app.alert.mail.enabled=true
logging.level.org.springframework.mail=DEBUG
logging.level.org.apache.commons.mail=DEBUG
logging.level.com.sun.mail=DEBUG
